// Function to load and display portfolio projects
async function loadPortfolio() {
  const masonryContainer = document.getElementById('masonry-portfolio');
  
  // If the container doesn't exist on this page, stop running
  if (!masonryContainer) return;

  try {
    // Fetch the JSON file generated by Decap CMS
    const response = await fetch('/content/projects.json');
    
    if (!response.ok) {
      throw new Error('Could not load projects data');
    }

    const data = await response.json();
    const projects = data.items;

    // Clear loading states or empty content
    masonryContainer.innerHTML = '';

    // Loop through each project from the CMS and create the HTML
    projects.forEach((project, index) => {
      
      // Alternate delays for the fade-up animation (1 or 2)
      const delayClass = index % 2 === 0 ? 'delay-1' : 'delay-2';

      const projectHTML = `
        <div class="masonry-item fade-up ${delayClass}">
          <img src="${project.image}" alt="${project.title}">
          <div class="masonry-overlay">
            <h3>${project.title}</h3>
            <p>${project.subtitle}</p>
          </div>
        </div>
      `;
      
      // Inject the HTML into the container
      masonryContainer.innerHTML += projectHTML;
    });

  } catch (error) {
    console.error("Error loading portfolio:", error);
    masonryContainer.innerHTML = '<p>Projects coming soon...</p>';
  }
}

// Run the function when the page loads
document.addEventListener('DOMContentLoaded', loadPortfolio);