backend:
  name: git-gateway
  branch: main

media_folder: "images/portfolio"
public_folder: "/images/portfolio"

collections:
  - name: "works"
    label: "Τα Έργα μας"
    folder: "content/works"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Τίτλος Έργου", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Φωτογραφία Έργου", name: "image", widget: "image" }
      - { label: "Περιγραφή", name: "body", widget: "markdown" }