backend:
  name: git-gateway
  branch: main # Η ονομασία του branch σου στο GitHub

media_folder: "images/portfolio" # Πού θα αποθηκεύονται οι φωτογραφίες
public_folder: "/images/portfolio" # Το path που θα βλέπει η HTML

collections:
  - name: "works" # Το όνομα της ενότητας
    label: "Τα Έργα μας" # Αυτό που θα βλέπει ο πελάτης
    folder: "content/works" # Πού θα αποθηκεύονται τα αρχεία (π.χ. ως .json ή .md)
    create: true # Επιτρέπει στον πελάτη να προσθέτει νέα έργα
    slug: "{{title}}" # Το όνομα του αρχείου θα είναι ο τίτλος του έργου
    fields: # ΕΔΩ ΟΡΙΖΕΙΣ ΤΙ ΜΠΟΡΟΥΝ ΝΑ ΑΛΛΑΞΟΥΝ
      - { label: "Τίτλος Έργου", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Φωτογραφία Έργου", name: "image", widget: "image" }
      - { label: "Περιγραφή", name: "body", widget: "markdown" }`